#!/usr/bin/env bash
set -ex

# compile
eosiocpp -o ../src/contracts/peerania/peerania.wast ../src/contracts/peerania/peerania.cpp 

# generate abi
eosiocpp -g ../src/contracts/peerania/peerania.abi ../src/contracts/peerania/peerania.cpp