#!/usr/bin/env bash
set -ex

EOS_NODE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cleos set contract peeranhamain $EOS_NODE_DIR/../src/contracts/peeranha.main
cleos set contract peeranhatken $EOS_NODE_DIR/../src/contracts/peeranha.token