#!/usr/bin/env bash
set -ex

#create wallet with name eosio
cleos wallet create --name default --to-console

#import private key for system eosio account
cleos wallet import --private-key 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3

#loading bios contract 
cleos set contract eosio ../eos/build/contracts/eosio.bios -p eosio