#!/usr/bin/env bash
set -ex

#create wallet with name eosio
./cl wallet create

#import private key for system eosio account
./cl wallet import 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3

#loading bios contract 
./cl set contract eosio ../eos/build/contracts/eosio.bios -p eosio

#import private key for code account and create account
./cl wallet import 5JUnu1jgVifdznEHpc9eVedpLXsyDPwu69xziMm9ZvbRSkVKEda
./cl create account eosio peerania.dev EOS5hhovSUZFZQPdvVvtCU9JjjZuuoyyQLG8EoY83UTELZtNMRz1b EOS5hhovSUZFZQPdvVvtCU9JjjZuuoyyQLG8EoY83UTELZtNMRz1b

#import private key for bob account and create account
./cl wallet import 5KgZw1vCGLSvwQUPFWeBxJFeYHuhQvz6XLa5p6vupwpwhFbaLLF
./cl create account eosio bob EOS7KerSuDMDGVvFi7v4svgMVALQYFyoyDgPJwRW4nzENGESnD9W1 EOS7KerSuDMDGVvFi7v4svgMVALQYFyoyDgPJwRW4nzENGESnD9W1

#import private key for alice account and create account
./cl wallet import 5JV2aCujE9j5dUkFKJGtyzeTsgMAHCovQ8QhxKHd9eZpJDfMDmZ
./cl create account peerania.dev alice EOS5hhovSUZFZQPdvVvtCU9JjjZuuoyyQLG8EoY83UTELZtNMRz1b EOS5hhovSUZFZQPdvVvtCU9JjjZuuoyyQLG8EoY83UTELZtNMRz1b

#error
./cl set account permission alice active '{"threshold":2,"keys":[],"accounts":[{"permission":{"actor":"peerania.dev","permission":"active"},"weight":1},{"permission":{"actor":"bob","permission":"active"},"weight":1}],"waits":[]}' owner -p alice@owner