#!/usr/bin/env bash
set -ex

cleos push action peerania.dev registeracc '{"user": "bob", "display_name": "Bobby", "ipfs_profile": "QmYBPXQMG32aUVqtMuptyR4dzgjykmBozyuDbvRGXxc1DK"}' -p bob
cleos push action peerania.dev registeracc '{"user": "carol", "display_name": "Carol", "ipfs_profile": "Qmc7Cq35A27VN4ft9UfbQ4D5azGA6g2GKTEAyC6sZjsDK9"}' -p carol
cleos push action peerania.dev registeracc '{"user": "user1", "display_name": "Roman", "ipfs_profile": "QmYBPXQMG32aUVqtMuptyR4dzgjykmBozyuDbvRGXxc1DK"}' -p user1
cleos push action peerania.dev setaccrtmpc '{"user": "bob", "rating": 3000, "moderation_points": 10}' -p bob
cleos push action peerania.dev setaccrtmpc '{"user": "user1", "rating": 3000, "moderation_points": 100}' -p user1
cleos push action peerania.dev followcomm '{"user": "user1", "community_id": "1"}' -p user1
cleos push action peerania.dev crcommunity '{"user": "bob", "name": "JJQJQJ", "ipfs_description": "QmPkZZtizV8Qat2Y9HkBWmgEX1L8p6VJZi1c6A2cf4vyfu", "suggested_tags": [
    {"name": "TAG1", "ipfs_description": "QmZrh8RVZwmX8H1DCUgNZ486U9HKsApkFLnzCf5sP9Aa1M"},
    {"name": "TAG2", "ipfs_description": "QmZrh8RVZwmX8H1DCUgNZ486U9HKsApkFLnzCf5sP9Aa1M"},
    {"name": "TAG3", "ipfs_description": "QmZrh8RVZwmX8H1DCUgNZ486U9HKsApkFLnzCf5sP9Aa1M"},
    {"name": "TAG4", "ipfs_description": "QmZrh8RVZwmX8H1DCUgNZ486U9HKsApkFLnzCf5sP9Aa1M"},
    {"name": "TAG5", "ipfs_description": "QmZrh8RVZwmX8H1DCUgNZ486U9HKsApkFLnzCf5sP9Aa1M"}]}' -p bob
cleos push action peerania.dev crtag '{"user": "bob", "community_id": 1, "name": "JJQJQJ", "ipfs_description": "QmPkZZtizV8Qat2Y9HkBWmgEX1L8p6VJZi1c6A2cf4vyfu"}' -p bob

cleos push action peerania.dev setaccrtmpc '{"user": "alice", "rating": 100, "moderation_points": 10}' -p alice
cleos push action peerania.dev setaccrtmpc '{"user": "bob", "rating": 200, "moderation_points": 10}' -p bob
cleos push action peerania.dev setaccrtmpc '{"user": "carol", "rating": 150, "moderation_points": 10}' -p carol

cleos push action peerania.dev postquestion '{"user":"alice", "title":"Alice question about life", "ipfs_link":"QmQtgrRFXpLrzfDSVDzMsVHN7NgMJ3MhNYgbTUXSg8NYJb"}' -p alice
cleos push action peerania.dev postanswer '{"user":"bob", "question_id":0, "ipfs_link":"QmYwd7TPMJEP1vtgVdhQiGjSjjuhUrDVGccQAWvAJgRPe9"}' -p bob
cleos push action peerania.dev postcomment '{"user":"carol", "question_id":0, "answer_id": 0, "ipfs_link":"QmTMZCVQKui85eB6osHwjknSFsgpEP7L8J4rCss7S8PdNR"}' -p carol
cleos push action peerania.dev postcomment '{"user":"carol", "question_id":0, "answer_id": 1, "ipfs_link":"QmNUusxFKjGNst57nXDGuBEXgkn7osQv2ZM4J9GG3EXr73"}' -p carol

cleos push action peerania.dev setaccrtmpc '{"user": "user1", "rating": 400, "moderation_points": 10}' -p alice