#!/usr/bin/env bash
set -ex

# remove all data files from previous run
rm -rf data

nodeos -e -p eosio --config-dir config --data-dir data --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::wallet_api_plugin --delete-all-blocks --contracts-console --http-validate-host false