version: 2
jobs:

  test:
    docker:
      - image: eosio/eosio-dev:latest
    working_directory: ~/ws
    steps:
      - attach_workspace:
          at: ~/ws
      - checkout:
          path:
            "peerania"
      - run:
          name: Package
          command: cd peerania && ./test
  deploy:
    docker:
      - image: eosio/eos-dev:v1.1.1
    working_directory: ~/ws

    steps:
      - checkout
      - attach_workspace:
          at: ~/ws
      - run:
          name: Package
          command: 'echo "Yay deploy!"'

workflows:
  version: 2

  test-build:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: develop
          requires:
            - test
