version: 2
jobs:

  test:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/ws
    steps:
      - attach_workspace:
          at: ~/ws
      - checkout:
          path:
            "peerania"
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps1-{{ .Branch }}-{{ checksum "peerania/requirements.txt" }}
      - run: # install and activate virtual environment with pip
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r peerania/requirements.txt
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "peerania/requirements.txt" }}
          paths:
            - "venv"
      - persist_to_workspace:
          root: .
          paths:
            - venv
      - run: # run tests
          name: Compile Contracts
          command: |
            peerania/compile
      - run: # run tests
          name: Tests
          command: |
            peerania/test
      - store_artifacts:
          path: test-reports/
          destination: tr1

  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/ws

    steps:
      - checkout
      - attach_workspace:
          at: ~/ws
      - run:
          name: Package
          command: 'echo "Yay deploy!"'

workflows:
  version: 2

  test-build:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: develop
          requires:
            - build
