#pragma once
#include <eosiolib/name.hpp>
#include "peerania_types.h"
// Limit to delte
namespace DeletionVotes
{
const int DELETION_VOTES_QUESTION = 1700;
const int DELETION_VOTES_ANSWER = 1500;
const int DELETION_VOTES_COMMENT = 1000;
} // namespace DeletionVotes

//Stub solution
#define VOTES_TO_CREATE_COMMUNITY 100
#define VOTES_TO_DELETE_COMMUNITY -35
#define VOTES_TO_CREATE_TAG 10
#define VOTES_TO_DELETE_TAG -10

#define MODERATION_POINTS_VOTE_DELETE 1

#define POST_QUESTION_REWARD 0
#define POST_ANSWER_REWARD 0
#define POST_COMMENT_REWARD 0
#define DELETE_OWN_QUESTION_REWARD -10
#define DELETE_OWN_ANSWER_REWARD -5
#define DELETE_OWN_COMMENT_REWARD 0
#define ACCEPT_ANSWER_AS_CORRECT_REWARD 2
#define UPVOTE_QUESTION_REWARD 0
#define DOWNVOTE_QUESTION_REWARD -1
#define UPVOTE_ANSWER_REWARD 0
#define DOWNVOTE_ANSWER_REWARD -1
#define VOTE_TO_DELETE_QUESTION_REWARD 0
#define VOTE_TO_DELETE_ANSWER_REWARD 0

#define QUESTION_UPVOTED_REWARD 5
#define ANSWER_UPVOTED_REWARD 10
#define ANSWER_ACCEPTED_AS_CORRECT_REWARD 15
#define QUESTION_DOWNVOTED_REWARD -2
#define ANSWER_DOWNVOTED_REWARD -2

#define QUESTION_DELETED_REWARD -15
#define ANSWER_DELETED_REWARD -10
#define COMMENT_DELETED_REWARD -5

#define MIN_RATING -100
#define MAX_RATING 2000000000
#define RATING_ON_CREATE 10

#define POST_QUESTION_ALLOWED 0
#define POST_ANSWER_OWN_ALLOWED 0
#define POST_ANSWER_ALLOWED 10
#define POST_COMMENT_OWN_ALLOWED 0
#define POST_COMMENT_ALLOWED 35
#define UPVOTE_ALLOWED 35
#define DOWNVOTE_ALLOWED 100
#define VOTE_FOR_DELETION_ALLOWED 100

#define CREATE_TAG_ALLOWED 500
#define CREATE_COMMUNITY_ALLOWED 2500
#define VOTE_CREATE_TAG_ALLOWED 35
#define VOTE_CREATE_COMMUNITY_ALLOWED 100
#define VOTE_DELETE_TAG_ALLOWED 35
#define VOTE_DELETE_COMMUNITY_ALLOWED 100

#define MODERATION_POINTS_PER_TAG 3
#define MODERATION_POINTS_PER_COMMUNITY 5

#define TAG_CREATED_REWARD 75
#define TAG_DELETED_REWARD -50

#define COMMUNITY_CREATED_REWARD 200
#define COMMUNITY_DELETED_REWARD -150

//Status
#define STATUS1_MODERATION_POINTS 1
#define STATUS2_MODERATION_POINTS 5
#define STATUS3_MODERATION_POINTS 10
#define STATUS4_MODERATION_POINTS 25
#define STATUS5_MODERATION_POINTS 50
#define STATUS6_MODERATION_POINTS 100

#define STATUS0_COMMENT_LIMIT 6
#define STATUS1_COMMENT_LIMIT 10
#define STATUS2_COMMENT_LIMIT 14
#define STATUS3_COMMENT_LIMIT 18
#define STATUS4_COMMENT_LIMIT 22
#define STATUS5_COMMENT_LIMIT 26
#define STATUS6_COMMENT_LIMIT 30

#define STATUS0_QUESTION_LIMIT 3
#define STATUS1_QUESTION_LIMIT 5
#define STATUS2_QUESTION_LIMIT 6
#define STATUS3_QUESTION_LIMIT 7
#define STATUS4_QUESTION_LIMIT 8
#define STATUS5_QUESTION_LIMIT 9
#define STATUS6_QUESTION_LIMIT 10

//Account period
#define ACCOUNT_STAT_RESET_PERIOD 259200 // 3 Days
#define BAN_RATING_INCREMENT_PER_PERIOD 6

//Account report reset time
#define MIN_FREEZE_PERIOD 302400           // 3.5 Days
#define REPORT_RESET_PERIOD 2592000        // 30 Days
#define REPORT_POWER_RESET_PERIOD 10368000 // 120 Days
#define POINTS_TO_FREEZE 90
#define MODERATION_POINTS_REPORT_PROFILE 2
#define MAX_FREEZE_PERIOD_MULTIPLIER 6