#pragma once

// Limit to delte
#if STAGE == 1 || STAGE == 2
#define REPORT_POINTS_QUESTION 7
#define REPORT_POINTS_ANSWER 5
#define REPORT_POINTS_COMMENT 3
#else
#define REPORT_POINTS_QUESTION 150
#define REPORT_POINTS_ANSWER 125
#define REPORT_POINTS_COMMENT 50
#endif

// EXPERT QUESTION
#define ANSWER_ACCEPTED_AS_CORRECT_REWARD 15
#define ACCEPT_ANSWER_AS_CORRECT_REWARD 2
#define UPVOTE_QUESTION_REWARD 0
#define DOWNVOTE_QUESTION_REWARD -1
#define UPVOTE_ANSWER_REWARD 0
#define DOWNVOTE_ANSWER_REWARD -1
#define QUESTION_UPVOTED_REWARD 5
#define ANSWER_UPVOTED_REWARD 10
#define QUESTION_DOWNVOTED_REWARD -2
#define ANSWER_DOWNVOTED_REWARD -2

// COMMON QUESTION
#define COMMON_ANSWER_ACCEPTED_AS_CORRECT_REWARD 3
#define ACCEPT_COMMON_ANSWER_AS_CORRECT_REWARD 1
#define COMMON_QUESTION_UPVOTED_REWARD 1
#define COMMON_ANSWER_UPVOTED_REWARD 2
#define COMMON_QUESTION_DOWNVOTED_REWARD -1
#define COMMON_ANSWER_DOWNVOTED_REWARD -1


// Stub solution
#if STAGE == 1 || STAGE == 2

#define VOTES_TO_CREATE_COMMUNITY 4
#define VOTES_TO_DELETE_COMMUNITY -3
#define VOTES_TO_CREATE_TAG 3
#define VOTES_TO_DELETE_TAG -2

#else

#define VOTES_TO_CREATE_COMMUNITY 100
#define VOTES_TO_DELETE_COMMUNITY -35
#define VOTES_TO_CREATE_TAG 10
#define VOTES_TO_DELETE_TAG -10

#endif


#define POST_QUESTION_REWARD 0
#define POST_ANSWER_REWARD 0
#define POST_COMMENT_REWARD 0
#define DELETE_OWN_QUESTION_REWARD -1
#define DELETE_OWN_ANSWER_REWARD -1
#define DELETE_OWN_COMMENT_REWARD 0
#define VOTE_TO_DELETE_QUESTION_REWARD 0
#define VOTE_TO_DELETE_ANSWER_REWARD 0

#define QUESTION_DELETED_REWARD -2
#define ANSWER_DELETED_REWARD -2
#define COMMENT_DELETED_REWARD -1

#define MIN_RATING -100
#define MAX_RATING 2000000000
#define RATING_ON_CREATE 10

#define POST_QUESTION_ALLOWED 0
#define POST_ANSWER_OWN_ALLOWED 0
#define POST_ANSWER_ALLOWED 0
#define POST_COMMENT_OWN_ALLOWED 0
#define POST_COMMENT_ALLOWED 35
#define UPVOTE_ALLOWED 35
#define DOWNVOTE_ALLOWED 100
#define VOTE_FOR_DELETION_ALLOWED 100


#define CREATE_TAG_ALLOWED 100
#define CREATE_COMMUNITY_ALLOWED 500
#define VOTE_CREATE_TAG_ALLOWED 35
#define VOTE_CREATE_COMMUNITY_ALLOWED 100
#define VOTE_DELETE_TAG_ALLOWED 35
#define VOTE_DELETE_COMMUNITY_ALLOWED 100
#define REPORT_PROFILE_ALLOWED 50

#define TAG_CREATED_REWARD 75
#define TAG_DELETED_REWARD -50

#define COMMUNITY_CREATED_REWARD 200
#define COMMUNITY_DELETED_REWARD -150

// Energy
#define ENERGY_DOWNVOTE_QUESTION 5
#define ENERGY_DOWNVOTE_ANSWER 3
#define ENERGY_UPVOTE_QUESTION 1
#define ENERGY_UPVOTE_ANSWER 1
#define ENERGY_FORUM_VOTE_CHANGE 1
#define ENERGY_POST_QUESTION 10
#define ENERGY_POST_ANSWER 6
#define ENERGY_POST_COMMENT 4
#define ENERGY_MODIFY_QUESTION 2
#define ENERGY_MODIFY_ANSWER 2
#define ENERGY_MODIFY_COMMENT 1
#define ENERGY_DELETE_QUESTION 2
#define ENERGY_DELETE_ANSWER 2
#define ENERGY_DELETE_COMMENT 1
#define ENERGY_MARK_ANSWER_AS_CORRECT 1
#define ENERGY_UPDATE_PROFILE 1
#define ENERGY_CREATE_TAG 75
#define ENERGY_CREATE_COMMUNITY 125
#define ENERGY_VOTE_COMMUNITY 1
#define ENERGY_VOTE_TAG 1
#define ENERGY_FOLLOW_COMMUNITY 1
#define ENERGY_REPORT_PROFILE 5
#define ENERGY_REPORT_QUESTION 3
#define ENERGY_REPORT_ANSWER 2
#define ENERGY_REPORT_COMMENT 1



namespace VoteItem
{
struct vote_resources_t
{
  int upvote_reward;
  int downvote_reward;
  int upvoted_reward;
  int downvoted_reward;
  int energy_upvote;
  int energy_downvote;
  int correct_answer;
  int first_answer;
  int answer_15_minutes;
};

const vote_resources_t question = {
    .upvote_reward = UPVOTE_QUESTION_REWARD,
    .downvote_reward = DOWNVOTE_QUESTION_REWARD,
    .upvoted_reward = QUESTION_UPVOTED_REWARD,
    .downvoted_reward = QUESTION_DOWNVOTED_REWARD,
    .energy_upvote = ENERGY_UPVOTE_QUESTION,
    .energy_downvote = ENERGY_DOWNVOTE_QUESTION,
    .correct_answer = ACCEPT_ANSWER_AS_CORRECT_REWARD,
    .first_answer = 0,
    .answer_15_minutes = 0,
};

const vote_resources_t answer = {
    .upvote_reward = UPVOTE_ANSWER_REWARD,
    .downvote_reward = DOWNVOTE_ANSWER_REWARD,
    .upvoted_reward = ANSWER_UPVOTED_REWARD,
    .downvoted_reward = ANSWER_DOWNVOTED_REWARD,
    .energy_upvote = ENERGY_UPVOTE_ANSWER,
    .energy_downvote = ENERGY_DOWNVOTE_ANSWER,
    .correct_answer = ANSWER_ACCEPTED_AS_CORRECT_REWARD,
    .first_answer = (int)(ANSWER_UPVOTED_REWARD * 0.5),
    .answer_15_minutes = (int)(ANSWER_UPVOTED_REWARD * 0.5),
};

const vote_resources_t common_question = {
    .upvote_reward = UPVOTE_QUESTION_REWARD,
    .downvote_reward = DOWNVOTE_QUESTION_REWARD,
    .upvoted_reward = COMMON_QUESTION_UPVOTED_REWARD,
    .downvoted_reward = COMMON_QUESTION_DOWNVOTED_REWARD,
    .energy_upvote = ENERGY_UPVOTE_QUESTION,
    .energy_downvote = ENERGY_DOWNVOTE_QUESTION,
    .correct_answer = ACCEPT_COMMON_ANSWER_AS_CORRECT_REWARD,
    .first_answer = 0,
    .answer_15_minutes = 0,
};

const vote_resources_t common_answer = {
    .upvote_reward = UPVOTE_ANSWER_REWARD,
    .downvote_reward = DOWNVOTE_ANSWER_REWARD,
    .upvoted_reward = COMMON_ANSWER_UPVOTED_REWARD,
    .downvoted_reward = COMMON_ANSWER_DOWNVOTED_REWARD,
    .energy_upvote = ENERGY_UPVOTE_ANSWER,
    .energy_downvote = ENERGY_DOWNVOTE_ANSWER,
    .correct_answer = COMMON_ANSWER_ACCEPTED_AS_CORRECT_REWARD,
    .first_answer = (int)(COMMON_ANSWER_UPVOTED_REWARD * 0.5),
    .answer_15_minutes = (int)(COMMON_ANSWER_UPVOTED_REWARD * 0.5),
};
} // namespace VoteItem

// Status 


